---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kiali${NAME_SUFFIX}
  labels:
    app: kiali
    version: ${VERSION_LABEL}
rules:
- apiGroups: [""]
  attributeRestrictions: null
  resources:
  - configmaps
  - namespaces
  - nodes
  - pods
  - projects
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups: ["config.istio.io"]
  attributeRestrictions: null
  resources:
  - routerules
  verbs:
  - get
  - list
  - watch
